import type { RuleConfidencePolicy } from '@/types';

export const RULE_CONFIDENCE_POLICIES: Record<string, RuleConfidencePolicy> = {
  'netlist.power-short.direct': {
    ruleId: 'netlist.power-short.direct',
    defaultSeverity: 'error',
    defaultConfidence: 'confirmed',
    falsePositiveRisk: 'low',
    suppressible: false,
    evidenceRequirements: {
      observedFactsMin: 2,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'bus.i2c-impedance-voltage.missing-pullup': {
    ruleId: 'bus.i2c-impedance-voltage.missing-pullup',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'netlist.led-current-limit-missing': {
    ruleId: 'netlist.led-current-limit-missing',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'electrical.logic-level.overvoltage': {
    ruleId: 'electrical.logic-level.overvoltage',
    defaultSeverity: 'error',
    defaultConfidence: 'confirmed',
    falsePositiveRisk: 'low',
    suppressible: false,
    evidenceRequirements: {
      observedFactsMin: 4,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'part-master.level-shifter-path-incomplete': {
    ruleId: 'part-master.level-shifter-path-incomplete',
    defaultSeverity: 'info',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'high',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'part-master.signal-level-mismatch': {
    ruleId: 'part-master.signal-level-mismatch',
    defaultSeverity: 'error',
    defaultConfidence: 'confirmed',
    falsePositiveRisk: 'low',
    suppressible: false,
    evidenceRequirements: {
      observedFactsMin: 4,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'part-master.protection-path-missing': {
    ruleId: 'part-master.protection-path-missing',
    defaultSeverity: 'info',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'part-master.level-shifter-side-mismatch': {
    ruleId: 'part-master.level-shifter-side-mismatch',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 4,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'part-master.same-net-bias-missing': {
    ruleId: 'part-master.same-net-bias-missing',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'part-master.strap-bias-missing': {
    ruleId: 'part-master.strap-bias-missing',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'part-master.decoupling-missing': {
    ruleId: 'part-master.decoupling-missing',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'part-master.bias-resistor-missing': {
    ruleId: 'part-master.bias-resistor-missing',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'clock.crystal-load-cap-missing': {
    ruleId: 'clock.crystal-load-cap-missing',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'clock.clock-source-review': {
    ruleId: 'clock.clock-source-review',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'power.regulator-max-input': {
    ruleId: 'power.regulator-max-input',
    defaultSeverity: 'error',
    defaultConfidence: 'confirmed',
    falsePositiveRisk: 'low',
    suppressible: false,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'power.regulator-max-input-unknown': {
    ruleId: 'power.regulator-max-input-unknown',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'power.source-collision': {
    ruleId: 'power.source-collision',
    defaultSeverity: 'error',
    defaultConfidence: 'confirmed',
    falsePositiveRisk: 'low',
    suppressible: false,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'power.usb-backpower-risk': {
    ruleId: 'power.usb-backpower-risk',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'power.bulk-cap-wireless': {
    ruleId: 'power.bulk-cap-wireless',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'power.reverse-polarity-protection-missing': {
    ruleId: 'power.reverse-polarity-protection-missing',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'power.regulator-thermal': {
    ruleId: 'power.regulator-thermal',
    defaultSeverity: 'error',
    defaultConfidence: 'confirmed',
    falsePositiveRisk: 'low',
    suppressible: false,
    evidenceRequirements: {
      observedFactsMin: 4,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'thermal.via-copper-review': {
    ruleId: 'thermal.via-copper-review',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'power.regulator-headroom': {
    ruleId: 'power.regulator-headroom',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 4,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'power.rail-over-budget': {
    ruleId: 'power.rail-over-budget',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'power.rail-low-headroom': {
    ruleId: 'power.rail-low-headroom',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'bus.i2c-pullup-missing': {
    ruleId: 'bus.i2c-pullup-missing',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'electrical.nc-pin-violation': {
    ruleId: 'electrical.nc-pin-violation',
    defaultSeverity: 'error',
    defaultConfidence: 'confirmed',
    falsePositiveRisk: 'low',
    suppressible: false,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'electrical.reserved-pin-violation': {
    ruleId: 'electrical.reserved-pin-violation',
    defaultSeverity: 'error',
    defaultConfidence: 'confirmed',
    falsePositiveRisk: 'low',
    suppressible: false,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireHowToVerify: true,
    },
  },
  'electrical.symbol-footprint-family-mismatch': {
    ruleId: 'electrical.symbol-footprint-family-mismatch',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 4,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'mcu.boot-strap-audit': {
    ruleId: 'mcu.boot-strap-audit',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'reset.por-supervisor-review': {
    ruleId: 'reset.por-supervisor-review',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'signal.mixed-voltage-tolerance-review': {
    ruleId: 'signal.mixed-voltage-tolerance-review',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'imported.power-pin-unconnected': {
    ruleId: 'imported.power-pin-unconnected',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'imported.ground-pin-unconnected': {
    ruleId: 'imported.ground-pin-unconnected',
    defaultSeverity: 'error',
    defaultConfidence: 'strong-inference',
    falsePositiveRisk: 'medium',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'imported.symbol-isolated': {
    ruleId: 'imported.symbol-isolated',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'high',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 2,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
  'imported.sheet-frame-overlap': {
    ruleId: 'imported.sheet-frame-overlap',
    defaultSeverity: 'warning',
    defaultConfidence: 'needs-review',
    falsePositiveRisk: 'high',
    suppressible: true,
    evidenceRequirements: {
      observedFactsMin: 3,
      requireVisualTargets: true,
      requireAssumptions: true,
      requireHowToVerify: true,
    },
  },
};

export function getRuleConfidencePolicy(ruleKey?: string | null): RuleConfidencePolicy | undefined {
  if (!ruleKey) {
    return undefined;
  }

  return RULE_CONFIDENCE_POLICIES[ruleKey];
}
