import { getInitialPins } from '@/constants/board-pins';
import { getDefaultWorkspaceMode } from '@/constants/product-surface';
import { DEFAULT_APP_LANGUAGE } from '@/lib/ui-language';
import type {
  AICodeGenerationMeta,
  AppLanguage,
  CloudProjectVisibility,
  InstalledProjectLibrary,
  CompilerManifest,
  ComponentTemplate,
  ComponentRuntimeState,
  ProjectComponentPowerModes,
  ProjectComponentUnusedPinModes,
  CustomComponentPackage,
  ImportedSchematicScene,
  ManualNetConnection,
  PlacedComponent,
  ProjectPowerInputMode,
  WorkspaceMode,
  WiringMode,
} from '@/types';
import { DEFAULT_BOARD_ID, DEFAULT_PROJECT_NAME } from '@/store/store-config';

export function buildDefaultProjectState(boardId = DEFAULT_BOARD_ID) {
  return {
    projectName: DEFAULT_PROJECT_NAME,
    appLanguage: DEFAULT_APP_LANGUAGE as AppLanguage,
    activeBoardId: boardId,
    pins: getInitialPins(boardId),
    components: [] as PlacedComponent[],
    manualConnections: [] as ManualNetConnection[],
    ghostFixPreview: null,
    importedSchematicScene: null as ImportedSchematicScene | null,
    importedSchematicSource: null as string | null,
    integratedValidationJson: null,
    validationReviewDecisions: {},
    footprintPinPadOverrideCache: {},
    templateCache: {} as Record<string, ComponentTemplate>,
    installedLibraries: [] as InstalledProjectLibrary[],
    generatedCode: '',
    codeError: null as string | null,
    lastCodeGenerationMeta: null as AICodeGenerationMeta | null,
    componentRuntimeStates: {} as Record<string, ComponentRuntimeState>,
    lastCompilerManifest: null as CompilerManifest | null,
    customComponentPackages: [] as CustomComponentPackage[],
    isGuestStudentMode: false,
    cloudProjectId: null as string | null,
    cloudProjectTitle: DEFAULT_PROJECT_NAME,
    cloudVisibility: 'unlisted' as CloudProjectVisibility,
    cloudIsSaving: false,
    cloudIsOwner: true,
    cloudLastSavedAt: null as string | null,
    cloudLastValidationJobId: null as string | null,
    cloudValidationPersistStatus: 'idle' as const,
    cloudValidationPersistError: null as string | null,
    cloudError: null as string | null,
    cloudEditToken: null as string | null,
    powerInputMode: 'usb-5v' as ProjectPowerInputMode,
    componentPowerModes: {} as ProjectComponentPowerModes,
    componentUnusedPinModes: {} as ProjectComponentUnusedPinModes,
    workspaceMode: getDefaultWorkspaceMode() as WorkspaceMode,
    wiringMode: 'auto' as WiringMode,
    showGrid: true,
    showMinimap: true,
    schematicTheme: 'light' as const,
    importedSchematicViewMode: 'original' as const,
  };
}
