#!/usr/bin/env python3
"""Convert normalized component catalog JSON into Supabase-ready rows or SQL."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

COMPONENTS_COLUMNS: list[tuple[str, str]] = [
    ("id", "varchar(255)"),
    ("name", "varchar(255)"),
    ("category", "varchar(50)"),
    ("description", "text"),
    ("icon", "varchar(100)"),
    ("compatible_voltage", "varchar(20)"),
    ("required_pins", "jsonb"),
    ("library_includes", "text[]"),
    ("simulation_model", "jsonb"),
    ("schematic_model", "jsonb"),
    ("pcb_model", "jsonb"),
    ("dependencies", "jsonb"),
    ("ai_hints", "jsonb"),
    ("design", "jsonb"),
    ("code", "jsonb"),
    ("library_source", "varchar(50)"),
    ("default_value", "varchar(100)"),
    ("datasheet_status", "varchar(50)"),
    ("popularity_rank", "integer"),
    ("package_version", "varchar(50)"),
]

LEGACY_COMPONENTS_MASTER_COLUMNS: list[tuple[str, str]] = [
    ("id", "varchar(255)"),
    ("name", "varchar(255)"),
    ("category", "varchar(50)"),
    ("description", "text"),
    ("icon", "varchar(100)"),
    ("compatible_voltage", "varchar(20)"),
    ("default_value", "varchar(100)"),
    ("required_pins", "jsonb"),
    ("library_includes", "text[]"),
    ("dependencies", "jsonb"),
    ("ai_hints", "jsonb"),
    ("design", "jsonb"),
    ("schematic", "jsonb"),
    ("pcb", "jsonb"),
    ("code", "jsonb"),
    ("package_version", "varchar(50)"),
    ("library_source", "varchar(50)"),
    ("datasheet_status", "varchar(50)"),
    ("popularity_rank", "integer"),
]


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_row(entry: dict[str, Any], table: str) -> dict[str, Any]:
    base = {
        "id": entry["id"],
        "name": entry["name"],
        "category": entry.get("category", "SENSOR"),
        "description": entry.get("description", f'{entry["name"]} component'),
        "icon": entry.get("icon", "Microchip"),
        "compatible_voltage": entry.get("compatibleVoltage", "BOTH"),
        "required_pins": entry.get("requiredPins", []),
        "library_includes": entry.get("libraryIncludes", []),
        "dependencies": entry.get("dependencies"),
        "ai_hints": entry.get("aiHints"),
        "design": entry.get("design"),
        "code": entry.get("code"),
        "library_source": entry.get("librarySource", "core"),
        "default_value": entry.get("defaultValue"),
        "datasheet_status": (entry.get("design") or {}).get("datasheetStatus"),
        "popularity_rank": entry.get("popularityRank"),
        "package_version": entry.get("packageVersion"),
    }

    if table == "components":
        base.update({
            "simulation_model": entry.get("simulation"),
            "schematic_model": entry.get("schematic"),
            "pcb_model": entry.get("pcb"),
        })
    else:
        base.update({
            "schematic": entry.get("schematic"),
            "pcb": entry.get("pcb"),
        })

    return base


def build_upsert_sql(table: str, rows: list[dict[str, Any]]) -> str:
    columns = COMPONENTS_COLUMNS if table == "components" else LEGACY_COMPONENTS_MASTER_COLUMNS
    conflict_column = "id"
    column_names = ", ".join(column for column, _ in columns)
    recordset = ",\n      ".join(f"{column} {pg_type}" for column, pg_type in columns)
    update_assignments = ",\n  ".join(
        f"{column} = excluded.{column}" for column, _ in columns if column != conflict_column
    )
    payload = json.dumps(rows, ensure_ascii=False, indent=2)
    tag = f"{table}_seed"
    while f"${tag}$" in payload:
        tag += "_x"
    payload_literal = f"${tag}$" + payload + f"${tag}$"

    return "\n".join([
        "-- Generated by catalog_to_supabase.py",
        "with seed_rows as (",
        "  select *",
        f"  from jsonb_to_recordset({payload_literal}::jsonb) as rows(",
        f"      {recordset}",
        "  )",
        ")",
        f"insert into public.{table} ({column_names})",
        f"select {column_names}",
        "from seed_rows",
        f"on conflict ({conflict_column}) do update set",
        f"  {update_assignments};",
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Supabase seed rows or import SQL from component JSON.")
    parser.add_argument("input", help="Path to normalized component array JSON.")
    parser.add_argument("--output", required=True, help="Output JSONL path.")
    parser.add_argument("--table", choices=["components", "components_master"], default="components")
    parser.add_argument("--format", choices=["jsonl", "sql"], default="jsonl")
    args = parser.parse_args()

    entries = read_json(Path(args.input))
    if not isinstance(entries, list):
        raise SystemExit("Input JSON must be an array.")

    rows = [
        normalize_row(entry, args.table)
        for entry in entries
        if isinstance(entry, dict) and entry.get("id") and entry.get("name")
    ]
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    if args.format == "sql":
        output.write_text(build_upsert_sql(args.table, rows), encoding="utf-8")
    else:
        output.write_text("\n".join(json.dumps(row, ensure_ascii=False) for row in rows) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
